version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
  frontend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}
  mysql:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}

services:
# Workspace Utilities #####################################
  workspace:
    build:
      context: ./workspace
      args:
        # Versions
        - WORKSPACE_COMPOSER_VERSION=${WORKSPACE_COMPOSER_VERSION}
        - WORKSPACE_NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - WORKSPACE_PHP_VERSION=${WORKSPACE_PHP_VERSION}
        # Settings
        - APP_LARAVEL_PATH=${APP_LARAVEL_PATH}
        - GIT_EMAIL=${WORKSPACE_GIT_USER_EMAIL}
        - GIT_NAME=${WORKSPACE_GIT_USER_NAME}
        - PGID=${WORKSPACE_PGID}
        - PUID=${WORKSPACE_PUID}
        - TZ=${WORKSPACE_TIMEZONE}
        # Install
        - INSTALL_NPM_VUE_CLI=${WORKSPACE_INSTALL_NPM_VUE_CLI}
        - INSTALL_NPM_QUASAR_CLI=${WORKSPACE_INSTALL_NPM_QUASAR_CLI}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    networks:
      - backend
      - frontend

# PHP-FPM #################################################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    expose:
      - "9000"
    depends_on:
      - workspace
    networks:
      - backend

# NGINX Server ############################################
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - backend
      - frontend

# MariaDB #################################################
  mariadb:
    build: ./mariadb
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - backend

# MySQL ###################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

# PhpMyAdmin ##############################################
  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - backend
      - frontend
