FROM phpmyadmin/phpmyadmin

LABEL maintainer="Alley M. Carvalho <alleycarvalho@gmail.com>"

# Add volume for sessions to allow session persistence
VOLUME /sessions

# We expose phpMyAdmin on port 80
EXPOSE 80
